name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u ${MYSQL_USER} -p$(cat /run/secrets/db_password) --silent"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 3s
      start_interval: 2s

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    secrets:
      - db_password
      - credentials
      - wp_user_password
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kporceil/data/db

  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kporceil/data/wordpress

networks:
  inception:
    driver: bridge
