[www]

; L'utilisateur et groupe sous lesquels PHP-FPM exécute les scripts PHP
; "nobody" est l'utilisateur par défaut sur Alpine pour les services non-privilégiés
user  = nobody
group = nobody

; Adresse d'écoute FastCGI
; "0.0.0.0:9000" = écoute sur toutes les interfaces réseau, port 9000
; NGINX enverra ses requêtes PHP ici via le réseau Docker
listen = 0.0.0.0:9000

; Gestion du nombre de processus PHP enfants
; "dynamic" = PHP-FPM adapte le nombre de workers selon la charge
pm = dynamic

; Nombre max de processus PHP simultanés
pm.max_children = 5

; Nombre de processus démarrés au lancement
pm.start_servers = 2

; Minimum de processus en attente (idle)
pm.min_spare_servers = 1

; Maximum de processus en attente (idle)
pm.max_spare_servers = 3
